/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.98KB] > D:\portfolio\PROJECT6\public\models\scene-transformed.glb [43.37KB] (-990%)
Author: Raj prajapat (https://sketchfab.com/rajprajapat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-series-9-faabf430da8c4e21a5a326ad5c2746b6
Title: Apple Watch Series 9
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Image} scale={3.855} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
